### PR TITLE
Add `started at` field in task subview

### PR DESCRIPTION
**Pull request by mboussaa**

### CODE REVIEW

**Review by fviale — APPROVED** [review]
LGTM, remember to squash before merging

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by MaelAudren** [comment]
retest this please

**Comment by MaelAudren** [comment]
retest this please

**Comment by MaelAudren** [comment]
retest this please

**Comment by MaelAudren** [comment]
retest this please

**Comment by MaelAudren** [comment]
retest this please

**Comment by mboussaa** [comment]
retest this please

**Pull request merged**
