### PR TITLE
symbolic link should be in reverse order, i.e it should link from app to studio

### PR DESCRIPTION
**Pull request by EnesKilicaslan**
Symbolic link should be from SCHEDULING_HOME/dist/war/studio to STUDIO_HOME/app .

### CODE REVIEW

**Comment by tobwiens** [comment]
Hi EnesKilicaslan, 

thank you very much for posting this PR, yes you are right. The ln -s command is swapped, as the example below it demonstrates.

On top of it I find it a bit confusing to work with links, we could rewrite to make it more clear.

@ow2-proactive/developers can a second dev please validate this PR.


Thank you.

**Comment by tobwiens** [comment]
Retest this please

**Comment by tobwiens** [comment]
I will merge thise

**Comment by tobwiens** [comment]
We are currently in a code freeze, let's wait until the jenkins pipeline agrees with this patch and the code freeze is over.

**Comment by EnesKilicaslan** [comment]
@tobwiens Sorry, I got it wrong and thanks for the update. Alright, let's wait then.

**Comment by Mykhailenko** [comment]
retest this please

**Pull request merged**
