### PR TITLE
Add tooltip to Load History metric in RM portal

### PR DESCRIPTION
**Pull request by Mykhailenko**

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 20 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 13 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [RMStatsView.java#L127](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L127): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L131](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L131): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L159](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L159): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MAJOR][MAJOR] [RMStatsView.java#L185](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L185): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MAJOR][MAJOR] [RMStatsView.java#L228](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L228): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L233](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L233): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L286](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L286): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MINOR][MINOR] [RMStatsView.java#L26](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L26): Rename this package name to match the regular expression '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00120)
1. ![MINOR][MINOR] [RMStatsView.java#L76](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L76): Declare "nodeLineFreeId" on a separate line. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1659)
1. ![MINOR][MINOR] [RMStatsView.java#L76](https://github.com/ow2-proactive/scheduling-portal/blob/759b9cc9d6993d3e47404f5a9d3d6a4d384d06cf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L76): Declare "nodeLineBusyId" on a separate line. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1659)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Mykhailenko** [comment]
Retest this please

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 20 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 13 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [RMStatsView.java#L127](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L127): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L131](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L131): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L159](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L159): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MAJOR][MAJOR] [RMStatsView.java#L185](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L185): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MAJOR][MAJOR] [RMStatsView.java#L228](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L228): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L233](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L233): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L286](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L286): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MINOR][MINOR] [RMStatsView.java#L26](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L26): Rename this package name to match the regular expression '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00120)
1. ![MINOR][MINOR] [RMStatsView.java#L76](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L76): Declare "nodeLineFreeId" on a separate line. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1659)
1. ![MINOR][MINOR] [RMStatsView.java#L76](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L76): Declare "nodeLineBusyId" on a separate line. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1659)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 20 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 13 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [RMStatsView.java#L127](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L127): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L131](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L131): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L159](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L159): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MAJOR][MAJOR] [RMStatsView.java#L185](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L185): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MAJOR][MAJOR] [RMStatsView.java#L228](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L228): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L233](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L233): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [RMStatsView.java#L286](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L286): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MINOR][MINOR] [RMStatsView.java#L26](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L26): Rename this package name to match the regular expression '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00120)
1. ![MINOR][MINOR] [RMStatsView.java#L76](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L76): Declare "nodeLineFreeId" on a separate line. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1659)
1. ![MINOR][MINOR] [RMStatsView.java#L76](https://github.com/ow2-proactive/scheduling-portal/blob/6d4594ee1613c6c1c56ef871d943f6bedcdcfcbf/rm-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/client/RMStatsView.java#L76): Declare "nodeLineBusyId" on a separate line. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1659)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
