### PR TITLE
Point documentation to dev when Snapshot version

### PR DESCRIPTION
**Pull request by tobwiens**
Point documentation to dev when Snapshot version

Problem:
- Documentation links of the SNAPSHOT version were pointing to the doc.activeeon.com/latest

Solution:
- Point the documentation links to doc.activeeon.com/dev

### CODE REVIEW

**Comment by tobwiens** [comment]
@ow2-proactive/developers Two reviews please.

**Comment by tobwiens** [comment]
@ow2-proactive/developers Two reviews please.

**Comment by marcocast** [comment]
retest this please

**Comment by tobwiens** [comment]
Retest this please

**Comment by tobwiens** [comment]
Retest this please

**Comment by tobwiens** [comment]
Retest this please

**Pull request merged**
